### ISSUE TITLE
App crashes when more than 10 windows are "active"

### ISSUE THREAD

**Issue by blockarchitech** [pebble-dev/pebblejs#6]
When more than 10 windows are registered (and are being used), any pebblejs app will crash unexplainably.

> (cc: @Willow-Systems)

**Comment by Willow-Systems** [comment]
Ooh interesting. Do you know if it affects Diorite? I know the issues on my home assistant app don't

**Comment by BlockArchitech** [comment]
Unfortunately I do not have a diorite watch to test with. I can't test aplite either, as my classic died a little bit ago.

**Comment by blockarchitech** [comment]
I think I've narrowed this down to a memory allocation issue. In my recent commit [77bf74b](https://github.com/pebble-dev/pebblejs/commit/77bf74b2804564187f25bb741ca023704d77cc29) I added a safer version of malloc. I'm going to try out the home assistant app and see if any errors arise using this newer version.
