### ISSUE TITLE
[docs] Navigation sorts things randomly (sometimes)

### ISSUE THREAD

**Issue by blockarchitech** [pebble-dev/pebblejs#9]
Sometimes, the navigation sidebar doesn't sort correctly.

cc: @JohnSpahr

**Comment by JohnSpahr** [comment]
Uh, that's weird.. guessing it might be a theme issue. Best option probably is to fork the theme and customize/improve it that way

**Comment by JohnSpahr** [comment]
I did try doing this earlier today but Jekyll is beyond me to be honest
